v_queue_calls_full
- callid => é o mesmo campo do uniqueid
- caller_id => número que ligou pra fila
- transfer => se houver transferência ele preenche com o destino
- status => status da ligação na fila
- timestamp => data/hora da ligação
- queue => número da fila
- position, original_position, key_pressed => não vão usar
- holdtime => tempo de espera
- duration => duração com conversação
- agente => dial do ramal que atendeu